# Dependencies
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

kramdown:
  input: GFM

pygments: true

# Permalinks
permalink: '/announcements/:title'

# Setup
title: Caliburn.Micro
tagline: 'Xaml made easy'
description: 'An opinionated MVVM framework for all Xaml platforms.'
url: http://caliburnmicro.com

author:
  name: 'Nigel Sampson'
  url: https://twitter.com/nigelsampson

paginate: 5
paginate_path: '/announcements/:num'

# Custom vars
version: 2.0.0-beta2

github:
  repo: https://github.com/caliburn-micro/caliburn.micro
